## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'kdc_101'
package-url = 'https://github.com/dntrubacs/pymodaq_plugins_kdc101.git'
description = 'Set of PyMoDAQ plugins for Thorlabs KDC101)'

author = 'Daniel-Iosif Trubacs'
author-email = 'dit1u20@soton.ac.uk'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ["pylablib", 'pymodaq>=4.0']
